name: Deploy

# Controls when the workflow will run
on:
  # Exemples de Eventos que o workflow pode escutar
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Evento para disparar manualmente o Workflow
  workflow_dispatch:

jobs:
  # Criado 2 jobs executados sequencialmente: test e build
  test:
    # The type of runner that the job will run on
    name: Teste
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executa os testes com Pytest
        run: | 
          pytest

  Deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "chapter-back-end" #Must be unique in Heroku
          heroku_email: "gabriel.lopes@outlook.com"
        env:
          FLASK_APP: app
        
         