name: Teste e Build

# Controls when the workflow will run
on:
  # Exemples de Eventos que o workflow pode escutar
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Evento para disparar manualmente o Workflow
  workflow_dispatch:

jobs:
  # Criado 2 jobs executados sequencialmente: test e build
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      -name: Set up Python 3.8
      -uses: actions/setup-python@v2
        -with:
          -python-version: "3.8"
      
      -name: Install Dependencies
       run: |
          pip -m pip install --upgrade pip
          pip install -r requirements.txt

      -name: Executa os testes com Pytest
        run: | 
          pytest

         