name: Teste e Build

# Controls when the workflow will run
on:
  # Exemples de Eventos que o workflow pode escutar
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Evento para disparar manualmente o Workflow
  workflow_dispatch:

jobs:
  # Criado 2 jobs executados sequencialmente: test e build
  test:
    # The type of runner that the job will run on
    name: Teste
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executa os testes com Pytest
        run: | 
          pytest

  build:
  
    name: Build
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
         